title: Jack Lucas
url: "https://lucasjacklucas.github.io"
baseurl: "https://lucasjacklucas.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ojroques/hugo-researcher"
footer_text: "By Jack Lucas. Based on Hugo Researcher"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Publications"
   link: "pubs"
 - name: "Papers"
   link: "wp"
 - name: "Group"
   link: "researchgroup"
 - name: "Resources"
   link: "resources"
 - name: "CV"
   link: "resume.pdf"
